### ISSUE TITLE
Disable image draw upon instantiation.

### ISSUE THREAD

**Issue by AnonymouX47** [pranavbaburaj/img#6]
https://github.com/pranavbaburaj/img/blob/1309c087b7b7aa5ade183c2800a0789d1529b6ab/image.py#L53-L54

I feel it's rather uncommon and unintuitive for object initialization (class instantiation) to have immediate size effects (e.g printing to the terminal in this case).
For instance, PIL doesn't display an image when you create a new image object, you have to explicitly call a method to do that... among so many others.

ObJect initialization has it's purpose... I think drawing the image will be better as a completely **explicit** action by calling the `draw_image()` method.

This concerns both the `__init__()` and `from_url()` methods and the _draw_ parameter in both.

**Comment by pranavbaburaj** [comment]
Yeah. thats right. But, my idea was to give the user chance for what to do. I think, the function call is unnecessary there. Maybe, we can remove it in the next release. Thanks for the suggestion

**Comment by pranavbaburaj** [comment]
Hey @AnonymouX47 , I have removed the automatic draw option ([`2409ee1`](https://github.com/pranavbaburaj/img/commit/2409ee1375aa59a66f014a565295372bc92b5d0f)). Would like to know what you think.

**Comment by AnonymouX47** [comment]
> Yeah. thats right. But, my idea was to give the user chance for what to do. I think, the function call is unnecessary there. Maybe, we can remove it in the next release. Thanks for the suggestion

You're welcome.

**Comment by AnonymouX47** [comment]
> Hey @AnonymouX47 , I have removed the automatic draw option ([`2409ee1`](https://github.com/pranavbaburaj/img/commit/2409ee1375aa59a66f014a565295372bc92b5d0f)). Would like to know what you think.

It's okay now.
